# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1de5cd762bffcf07545c97ce800874e284976b708b10cefbcac1664a1a1df7dfc57b8ce959bc85211913642d2418e15e24869d9934959df825d132aff2a48671

test:
  secret_key_base: 997aad344d8c1d5b9305d8458a3f509bea0f73a5d33829e6bdd91f2c1041db24089196111f098d74d4a49967480f07802a8f3ea1c43c01efaaf6e7760039a9db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
